version: '3'
services:
  frontend:
    build: ./client
    ports:
      - 3001:3000
    container_name: movietvorets_frontend
    env_file:
      - ./client/.env
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - 5001:5000
    container_name: movietvorets_backend
    env_file:
      - ./server/.env
